# Schema for the configuration files of the Small Message Coupon module.
#
smmg_coupon.settings:
  type: config_object
  label: 'Coupon Settings'
  mapping:
    message:
      type: text
      label: 'Message'